import fs from 'fs';

// Comprehensive Kurmanji-Latin to Badini Kurdish-Arabic Script rules & lexicon
// Built from the official Badini curriculum in docs/references/

export const BADINI_TERM_MAP: Record<string, string> = {
  // Common UI & Verbs
  'Hat tomarkirin': 'هاتە تۆمارکرن',
  'Pêvanê tomar bike': 'پێڤانێ تۆمار بکە',
  'tomar bike': 'تۆمار بکە',
  'Destpêkirin': 'دەستپێکرن',
  'Pewstandin': 'راوەستاندن',
  'Rawestandin': 'راوەستاندن',
  'Raweste': 'راوەستە',
  'Aram Be': 'راوەستە',
  'Rêk xistin': 'ژ نوی رێکبێخە',
  'Rêk bixe': 'ژ نوی رێکبێخە',
  'Guleyê Biavêje': 'گوللەیێ باڤێژە',
  'Biavêje': 'باڤێژە',
  'Haviştin': 'هاڤێتن',
  'Bikirtîne': 'کلیک بکە',
  'Nîşan bide': 'نیشان بدە',
  'Veşêre': 'ڤەشێڕە',
  'Vekirî': 'ڤەکری',
  'Girtî': 'گرتی',
  'Qutbûyî': 'قوتکری',
  'Qutkirî': 'قوتکری',
  'vekirina': 'ڤەکرنا',
  'girtina': 'گرتنا',
  'qutkirina': 'قوتکرنا',
  'girêdana': 'گرێدانا',
  'Biguhere': 'بگوهۆڕە',
  'guhertin': 'گوهۆڕین',
  'Guhertina': 'گوهۆڕینا',
  'Hilbijêre': 'هەلبژێڕە',
  'Hilbijartina': 'هەلبژارتنا',
  'Paqij bike': 'پاقژ بکە',
  'Rabe': 'رابە',
  'Daliqandî': 'هەلاویستی',
  'Daliqandin': 'هەلاویستن',
  'Noqbûn': 'نوقمبوون',
  'Noqbûyî': 'نوقمبووی',
  'Avjenî': 'سەرئاڤکەفتن',
  
  // Electrical
  'Çerxe': 'بازنە',
  'Çerxeya': 'بازنەیا',
  'çerxeyê': 'بازنەیێ',
  'çerxê': 'بازنەیێ',
  'çerxan': 'بازنەیان',
  'Mifte': 'مفتاح',
  'Mifteya': 'مفتاحا',
  'mifteyê': 'مفتاحێ',
  'Voltaj': 'ڤۆڵتیە',
  'Voltaja': 'ڤۆڵتیەیا',
  'voltajê': 'ڤۆڵتیەیێ',
  'Herikîn': 'تەزوو',
  'Herikîna': 'تەزوویا',
  'herikînê': 'تەزوویێ',
  'Berxwedan': 'بەرگری',
  'Berxwedana': 'بەرگریا',
  'berxwedanê': 'بەرگریێ',
  'Batarya': 'پاتری',
  'Bataryaya': 'پاتریا',
  'Çira': 'گلۆپ',
  'Çirayê': 'گلۆپێ',
  'Têl': 'تەل',
  'Têla': 'تەلا',
  
  // Physics concepts
  'Lez': 'لەزاتی',
  'Leza': 'لەزاتیا',
  'lezê': 'لەزاتیێ',
  'Lezdan': 'لەزدان',
  'Lezdana': 'لەزدانا',
  'Hêz': 'هێز',
  'Hêza': 'هێزا',
  'hêzê': 'هێزێ',
  'Enerjî': 'وزە',
  'Enerjiya': 'وزەیا',
  'enerjiyê': 'وزەیێ',
  'Tevger': 'لڤین',
  'Tevgera': 'لڤینا',
  'hevgerê': 'لڤینێ',
  'Mase': 'بارستە',
  'Maseya': 'بارستەیا',
  'maseyê': 'بارستەیێ',
  'Giranî': 'کێش',
  'Giraniya': 'کێشێ',
  'Dendik': 'چڕی',
  'Dendika': 'چڕیا',
  'Qebare': 'قەبارە',
  'Qebareya': 'قەبارێ',
  'Pestan': 'پەستان',
  'Pestana': 'پەستانا',
  'Germahî': 'گەرماتی',
  'Germahiya': 'گەرماتیا',
  'germahiyê': 'گەرماتیێ',
  'Asoyî': 'ئاسۆیی',
  'Sitûnî': 'ستوونی',
  'Goşe': 'گۆشە',
  'Goşeya': 'گۆشەیا',
  'goşeyê': 'گۆشەیێ',
  'Dirêjahî': 'درێژی',
  'Dirêjahiya': 'درێژیا',
  'dirêjahiyê': 'درێژیێ',
  'Bilindahî': 'بلنداهی',
  'Bilindahiya': 'بلنداهیا',
  'bilindahiyê': 'بلنداهیێ',
  'Dûrî': 'دووراتی',
  'Dûriya': 'دووراتیا',
  'Mewda': 'مەودا',
  'Mewdayê': 'مەودایێ',
  'Cihguherîn': 'لادان',
  'Cihguherîna': 'لادانا',
  'Şûna hevsengiyê': 'جهێ هەڤسەنگیێ',
  'Hevsengî': 'هەڤسەنگی',
  'hevsengiyê': 'هەڤسەنگیێ',
  'Dem': 'دەم',
  'Dema': 'دەمێ',
  'demê': 'دەمێ',
  'Frekans': 'فریکوێنسی',
  'Frekansa': 'فریکوێنسیا',
  'Pêl': 'پێل',
  'Pêla': 'پێلا',
  'Pêlên': 'پێلێن',
  'pêlan': 'پێلان',
  'Deng': 'دەنگ',
  'Dengê': 'دەنگێ',
  'Ronahî': 'رووناهی',
  'Ronahiya': 'رووناهیا',
  'ronahiyê': 'رووناهیێ',
  'Tîşk': 'تیشک',
  'Tîşka': 'تیشکا',
  'tîşkan': 'تیشکان',
  'Şikestin': 'شکەستن',
  'Şikestina': 'شکەستنا',
  'Vekolîn': 'ڤەکۆلین',
  'Vekolîna': 'ڤەکۆلینا',
  'Lêkolîn': 'لێگەڕیان',
  'Lêkolîna': 'لێگەڕیانا',
  'Armanc': 'ئارمانج',
  'Armanca': 'ئارمانجا',
  'armancê': 'ئارمانجێ',
  'Nîşander': 'نیشاندەر',
  'Grafîk': 'هێلکاری',
  'Grafîka': 'هێلکاریا',
  'Mîheng': 'رێکخستن',
  'Mîhengên': 'رێکخستنێن',
  'Encam': 'ئەنجام',
  'Encamên': 'ئەنجامێن',
  'Şirove': 'شڕۆڤە',
  'Şîrove': 'شڕۆڤە',
  'Şîrovekirina': 'شڕۆڤەکرنا',
  'Qanûn': 'یاسا',
  'Qanûna': 'یاسایا',
  'qanûnê': 'یاسایێ',
  'Qanûnên': 'یاسایێن',
  'Taybetmendî': 'تایبەتمەندی',
  'Taybetmendiyên': 'تایبەتمەندیێن',
  'Parametre': 'پێوەر',
  'Parametreyên': 'پێوەرێن',
  'Spîring': 'سپرینگ',
  'Spîringa': 'سپرینگا',
  'spîringê': 'سپرینگێ',
  'Dandûl': 'پاندۆل',
  'Dandûla': 'پاندۆلا',
  'dandûlê': 'پاندۆلێ',
  'Hawêjtî': 'هاوێژراو',
  'Hawêjtiyê': 'هاوێژراوی',
  'Hawêjtiyek': 'هاوێژراوەک',
  'Şilemenî': 'شلەمەنی',
  'Şilemeniyê': 'شلەمەنیێ',
  'Şilek': 'شلە',
  'Şilekê': 'شلەیێ',
  'Tişt': 'تەن',
  'Tiştê': 'تەنێ',
  'tiştan': 'تەنان',
  'Gerdîle': 'گەردیلە',
  'Gerdîleya': 'گەردیلەیا',
  'gerdîleyê': 'گەردیلەیێ',
  'Navok': 'ناڤۆک',
  'Navoka': 'ناڤۆکا',
  'navokê': 'ناڤۆکێ'
};

console.log("BADINI_TERM_MAP count:", Object.keys(BADINI_TERM_MAP).length);
