export const batch7: Record<string, any> = {
  static_balloons: {
    title: 'باڵۆنێن کارەبایا ساکن و جەمسەرگیری',
    shortDesc: 'ڤەکۆلینا کارەبایا ساکن، لێکخشاندنا باڵۆنێ دگەل تێلیسووفی (خوری)، گواستنەوەیا ئەلیکترۆنان، بارگاویکردن و جەمسەرگیریا کارەبایی یا دیوارێ بێ بارگە.',
    rubBalloon: 'باڵۆنێ ب خوریێ بخشینە 🎈',
    balloonCharge: 'بارگەیێ باڵۆنێ (q_balloon)',
    sweaterCharge: 'بارگەیێ خوریێ (q_sweater)',
    wallCharges: 'بارگەیێن سەر دیوارێ',
    polarizationEffect: 'جەمسەرگیریا کارەبایی: ئەلیکترۆنێن دیواری پاشڤە دچن و باڵۆن پێڤە دمینیت',
    attractionForce: 'هێزا کێشکرنێ بەرەڤ دیوارێ',
    releaseBalloon: 'باڵۆنێ بەردە',
    reset: 'ژ نوی رێکبێخە',
    varBalloonCharge: 'بارگەیێ باڵۆنێ (q)',
    notesText: 'کارەبایا ساکن و جەمسەرگیریا دیوارێ ب سەرکەفتیانە هاتنە تاقیکرن.',
    controlsTitle: 'رێکخستنێن کارەبایا ساکن'
  },
  stress_strain: {
    title: 'شەدین، ڤەکێشان و مۆدیۆلێ یۆنگی',
    shortDesc: 'ڤەکۆلینا تەشیاریا ماددەیان، شەدین (Stress σ = F/A)، کشان / ڤەکێشان (Strain ε = ΔL/L₀)، مۆدیۆلێ یۆنگی (Young Modulus E) و سنورێ تەشیاریێ.',
    materialSelect: 'ماددەیێ تاقیکرنێ (پۆڵا، ئەلەمنیۆم، مس، کاوچووک)',
    appliedForce: 'هێزا راکێشانێ (F)',
    originalLength: 'درێژیا دەستپێکێ (L₀)',
    crossSectionArea: 'رووبەرێ بڕگەی (A)',
    stress: 'شەدین (Stress σ = F / A)',
    strain: 'ڤەکێشان (Strain ε = ΔL / L₀)',
    elongation: 'زێدەبوونا درێژیێ (ΔL)',
    youngModulus: 'مۆدیۆلێ یۆنگی (E = σ / ε)',
    hookesRegion: 'دەڤەرا تەشیار (یاسایا هووکی کار دکەت)',
    plasticDeformation: '⚠️ گوهۆڕینا پلاستیكی (نازڤڕیتە باری پێشوو)',
    fracturePoint: '💥 خال شکەستنێ یا ماددەی!',
    reset: 'ژ نوی رێکبێخە',
    varStress: 'شەدینا سەپاندی (σ)',
    notesText: 'مۆدیۆلێ یۆنگی و تەشیاریا ماددەی ب دروستی هاتنە پێڤان.',
    controlsTitle: 'رێکخستنێن شەدین و ڤەکێشانێ'
  },
  thin_lenses: {
    title: 'هاوێنەیێن تەنک (قۆقز و قوپچاڵ)',
    shortDesc: 'ڤەکۆلینا دروستبوونا وێنەیان ب هاوێنەیا قۆقز (کۆکەرەوە) و قوپچاڵ (بەلاڤکەرەوە)، دووراتیا تەنێ ژ هاوێنەیێ، هاوکێشەیا گشتی یا هاوێنەیان و مەزنکرن.',
    lensType: 'جورێ هاوێنەیێ',
    convex: 'هاوێنەیا قۆقز (کۆکەرەوە f > 0)',
    concave: 'هاوێنەیا قوپچاڵ (بەلاڤکەرەوە f < 0)',
    focalLength: 'دووراتیا تیشکۆیی (f)',
    objectDistance: 'دووراتیا تەنێ (d_o)',
    objectHeight: 'بلنداهیا تەنێ (h_o)',
    imageDistance: 'دووراتیا وێنەی (d_i)',
    imageHeight: 'بلنداهیا وێنەی (h_i)',
    magnification: 'مەزنکرن (m = -d_i / d_o)',
    lensFormula: 'هاوکێشەیا هاوێنەیان: 1/f = 1/d_o + 1/d_i',
    realImage: 'وێنەیێ دروست (سەرەوژێر، د پشت هاوێنەیێدا)',
    virtualImage: 'وێنەیێ خەیالی (راستەڕێ، د پێش هاوێنەیێدا)',
    showPrincipalRays: 'سێ تیشکێن بینایی نیشان بدە',
    reset: 'ژ نوی رێکبێخە',
    varImageDistance: 'دووراتیا وێنەی ژ هاوێنەیێ (d_i)',
    notesText: 'وێنەیێن دروستبووی د هاوێنەیێن تەنکدا ب دروستی هاتنە شیکارکرن.',
    controlsTitle: 'رێکخستنێن هاوێنەیێن تەنک'
  },
  wave_on_a_string: {
    title: 'شەپۆل ل سەر بەندکێ (گرژی و لەرین)',
    shortDesc: 'ڤەکۆلینا لڤینا شەپۆلان ل سەر بەندکی، کارتێکرنا گرژیا بەندکی (Tension)، چڕیا هێلی یا بارستەی (μ)، فریکوێنسی و شەپۆلێن ڕاوەستیاو (Standing Waves).',
    stringTension: 'گرژیا بەندکی (T)',
    linearDensity: 'چڕیا هێلی یا بارستەی (μ = m / L)',
    frequency: 'فریکوێنسیا لەرینێ (f)',
    amplitude: 'فراوانیا پێلێ (A)',
    waveSpeed: 'لەزاتیا پێلێ (v = √(T/μ))',
    wavelength: 'درێژیا پێلێ (λ = v / f)',
    fixedEnd: 'دووماهیا بەستراو (Fixed End - ڤەگەڕیانا سەرەوژێر)',
    freeEnd: 'دووماهیا ئازاد (Free End - ڤەگەڕیانا سەرەوژوور)',
    standingWaves: 'شەپۆلێن ڕاوەستیاو (گرێ و دژەگرێ)',
    pulseMode: 'تەپڵێک (Pulse)',
    continuousMode: 'بەردەوام (Oscillate)',
    reset: 'ژ نوی رێکبێخە',
    varWaveSpeed: 'لەزاتیا پێلێ ل سەر بەندکی (v)',
    notesText: 'لەزاتیا پێلێ ل سەر بەندکی و گرژی ب سەرکەفتیانە هاتنە پێڤان.',
    controlsTitle: 'رێکخستنێن پێلا بەندکی'
  },
  resistance_in_wire: {
    title: 'بەرگریا تەلێ کارەبایی و بەرگرییا جۆری',
    shortDesc: 'ڤەکۆلینا یاسایا بەرگریا تەلێ کارەبایی (R = ρ · L / A)، کارتێکرنا درێژیا تەلێ، رووبەرێ بڕگەی و بەرگرییا جۆری یا ماددەی (Resistivity ρ).',
    resistivity: 'بەرگرییا جۆری یا ماددەی (Resistivity ρ)',
    wireLength: 'درێژیا تەلێ (L)',
    crossSectionArea: 'رووبەرێ بڕگەی یێ تەلێ (A)',
    resistance: 'بەرگریا کارەبایی (R = ρ · L / A)',
    resistanceFormula: 'هاوکێشە: R = ρ · L / A',
    materials: 'ماددەیێن تەلێ',
    copper: 'مس (ρ = 1.68 × 10⁻⁸ Ω·m)',
    aluminum: 'ئەلەمنیۆم (ρ = 2.65 × 10⁻⁸ Ω·m)',
    tungsten: 'تەنگستن (ρ = 5.6 × 10⁻⁸ Ω·m)',
    nichrome: 'نیکرۆم (ρ = 100 × 10⁻⁸ Ω·m)',
    longerWireNote: 'تەلا درێژتر -> بەرگریا زۆرتر',
    thickerWireNote: 'تەلا ئەستوورتر -> بەرگریا کێمتر',
    reset: 'ژ نوی رێکبێخە',
    varResistance: 'بەرگریا تەلێ (R)',
    notesText: 'بەرگریا تەلێ ب گوڕینی درێژی و ئەستووریێ ب سەرکەفتیانە هاتە پێڤان.',
    controlsTitle: 'رێکخستنێن بەرگریا تەلێ'
  },
  work_heat: {
    title: 'ئیش، گەرماتی و هاوتایێ میکانیکی یێ جوول',
    shortDesc: 'ڤەکۆلینا تاقیکرنا بەناوبانگی یا جوول، گوهۆڕینا کارێ میکانیکی (W = mgh) بۆ گەرماتی د ئاڤێدا (Q = mcΔT) و دۆزینەوەیا هاوتایێ میکانیکی (1 cal ≈ 4.184 J).',
    fallingMass: 'بارستەیا کێشی (m)',
    fallHeight: 'بلنداهیا کەفتنا کێشی (h)',
    waterMass: 'بارستەیا ئاڤێ (m_w)',
    workInput: 'ئیشێ میکانیکی یێ سەپاندی (W = m·g·h)',
    tempRise: 'بلندبوونا پلەیا گەرماتیێ (ΔT = W / (m_w · c))',
    jouleMechanicalEquivalent: 'هاوتایێ میکانیکی یێ جوول (Joule Equivalent J ≈ 4.184 J/cal)',
    dropWeights: 'کێشان بەردە بەرەڤ خوارێ دا کو چەرخ بزڤڕیت ⚙️',
    reset: 'ژ نوی رێکبێخە',
    varTempRise: 'بلندبوونا پلەیا گەرماتیێ (ΔT)',
    notesText: 'گوهۆڕینا ئیشێ میکانیکی بۆ گەرماتی و هاوتایێ جوول ب دروستی هاتە سەلماندن.',
    controlsTitle: 'رێکخستنێن ئیش و گەرماتیێ'
  }
};
