export const batch4: Record<string, any> = {
  gas_diffusion: {
    title: 'بەلاڤبوونا گازی و یاسایا گراهام',
    shortDesc: 'ڤەکۆلینا بەلاڤبوونا دوو گازێن جودا د بۆڕیەکێدا، کارتێکرنا بارستەیا مۆلی ل سەر لەزاتیا بەلاڤبوونێ و یاسایا گراهام (r₁/r₂ = √(M₂/M₁)).',
    gas1: 'گازا ئێکێ (Gas 1)',
    gas2: 'گازا دوویێ (Gas 2)',
    molarMass1: 'بارستەیا مۆلی ya 1 (M₁)',
    molarMass2: 'بارستەیا مۆلی ya 2 (M₂)',
    tubeLength: 'درێژیا بۆڕیێ (L)',
    temperature: 'پلەیا گەرماتیێ (T)',
    grahamLaw: 'یاسایا گراهام: r₁ / r₂ = √(M₂ / M₁)',
    collisionPoint: 'خالا بێکگەهشتنێ (Meeting Point)',
    startDiffusion: 'بەلاڤبوونا گازان دەستپێبکە 💨',
    reactionProduct: 'ماددەیێ بەرهەمهاتی ژ کارلێکێ (پەڕا سپی)',
    diffusionTime: 'دەمێ گەهشتنێ (t)',
    reset: 'ژ نوی رێکبێخە',
    varCollisionPoint: 'خالا بێکگەهشتنا دوو گازان د بۆڕیێدا (x)',
    notesText: 'خالا بێکگەهشتنا دوو گازان و یاسایا گراهام ب دروستی هاتە سەلماندن.',
    controlsTitle: 'رێکخستنێن بەلاڤبوونا گازی'
  },
  doppler_effect: {
    title: 'کاریگەریا دۆپلەر بۆ پێلێن دەنگی',
    shortDesc: 'ڤەکۆلینا گوهۆڕینا فریکوێنسیا بهیستی دەمێ سەرچاوەیێ دەنگی یان گوهگر دلڤن، سۆنیک بووم (Sonic Boom) و ژمارەیا ماخ.',
    sourceFreq: 'فریکوێنسیا سەرچاوەی (f₀)',
    sourceSpeed: 'لەزاتیا سەرچاوەی (v_s)',
    observerSpeed: 'لەزاتیا گوهگری (v_o)',
    soundSpeed: 'لەزاتیا دەنگی د هەوایدا (v)',
    observedFreq: 'فریکوێنسیا بهیستی یا گوهگری (f’)',
    machNumber: 'ژمارەیا ماخ (M = v_s / v)',
    approaching: 'سەرچاوە نێزیک دبیت (فریکوێنسی بلندتر لێدهێت ⬆️)',
    receding: 'سەرچاوە دوور دکەڤیت (فریکوێنسی نزمتر لێدهێت ⬇️)',
    sonicBoomShockwave: '⚠️ پێلا پەستانێ یا سۆنیک بووم (Mach Cone)!',
    dopplerFormula: 'هاوکێشە: f’ = f₀ · (v ± v_o) / (v ∓ v_s)',
    playDopplerSound: 'دەنگێ دۆپلەر ببیهیزە 🚗',
    reset: 'ژ نوی رێکبێخە',
    varObservedFreq: 'فریکوێنسیا بهیستی (f’)',
    notesText: 'کاریگەریا دۆپلەر و فریکوێنسیا بهیستی ب سەرکەفتیانە هاتە تۆمارکرن.',
    controlsTitle: 'رێکخستنێن کاریگەریا دۆپلەر'
  },
  electrical_transformer: {
    title: 'گۆڕەرێ کارەبایی و یاسایا فارادای',
    shortDesc: 'ڤەکۆلینا گۆڕەرێ بلندکەر و نزمکەر یێ کارەبایی، رێژەیا ژمارەیا بادانان، ڤۆڵتیەیا سەرەکی و لاوەکی، تەزوو و پاراستنا شیانێ.',
    primaryTurns: 'بادانێن دەستپێکێ (N_p)',
    secondaryTurns: 'بادانێن دوویێ (N_s)',
    primaryVoltage: 'ڤۆڵتیەیا دەستپێکێ (V_p)',
    secondaryVoltage: 'ڤۆڵتیەیا دوویێ (V_s)',
    turnsRatio: 'رێژەیا بادانان (N_s / N_p)',
    transformerType: 'جورێ گۆڕەری',
    stepUp: 'گۆڕەرێ بلندکەر (V_s > V_p)',
    stepDown: 'گۆڕەرێ نزمکەر (V_s < V_p)',
    isolation: 'گۆڕەرێ هاوسەنگ (V_s = V_p)',
    primaryCurrent: 'تەزوویا دەستپێکێ (I_p)',
    secondaryCurrent: 'تەزوویا دوویێ (I_s)',
    powerEfficiency: 'شیانا گشتی (P_p = P_s = V·I د گۆڕەرێ بێ کێماسیدا)',
    ironCore: 'ناڤۆکا ئاسنی (Iron Core)',
    transformerFormula: 'هاوکێشە: V_s / V_p = N_s / N_p = I_p / I_s',
    reset: 'ژ نوی رێکبێخە',
    varSecondaryVoltage: 'ڤۆڵتیەیا دوویێ یا گۆڕەری (V_s)',
    notesText: 'پەیوەندیا ناڤبەرا بادانان و ڤۆڵتیەیێ ب سەرکەفتیانە هاتە سەلماندن.',
    controlsTitle: 'رێکخستنێن گۆڕەرێ کارەبایی'
  },
  magnets_electromagnets: {
    title: 'موگناتیس و کارۆموگناتیس',
    shortDesc: 'ڤەکۆلینا بیاڤێ موگناتیسی یێ موگناتیسێ بەردەوام و کۆیلێ هەلگری تەزوو، کارتێکرنا ناڤۆکا ئاسنی و ژمارەیا بادانان.',
    batteryVoltage: 'ڤۆڵتیەیا پاتریێ (V)',
    coilTurns: 'ژمارەیا بادانێن تەلی (N)',
    ironCorePresent: 'ناڤۆکا ئاسنی (Iron Core)',
    magneticFieldStrength: 'هێزا بیاڤێ موگناتیسی (B)',
    compassResponse: 'ئاراستەیا دەرزییا قیبلەنمایێ',
    pickupPaperclips: 'کێشکرنا کلیپسێن کاعەزێ 📎',
    poleNorth: 'جەمسەرێ باکوور (N)',
    poleSouth: 'جەمسەرێ باشوور (S)',
    reverseCurrent: 'ئاراستەیا تەزوویێ پێچەوانە بکە',
    reset: 'ژ نوی رێکبێخە',
    varFieldStrength: 'چڕیا بیاڤێ موگناتیسی (B)',
    notesText: 'هێزا کارۆموگناتیسێ و بیاڤێ موگناتیسی ب سەرکەفتیانە هاتنە دیارکرن.',
    controlsTitle: 'رێکخستنێن کارۆموگناتیسێ'
  },
  electromagnet: {
    title: 'هێزا کارۆموگناتیسێ و تەزوویا کارەبایی',
    shortDesc: 'ڤەکۆلینا پەیوەندیا ناڤبەرا بڕێ تەزوویێ، ژمارەیا بادانان و هێزا کێشکرنا کارۆموگناتیسێ بۆ پارچەیێن کانزایی.',
    current: 'تەزوویا کارەبێ (I)',
    turns: 'ژمارەیا بادانان (N)',
    coreMaterial: 'ماددەیێ ناڤۆکێ',
    coreIron: 'ئاسن (توانایا موگناتیسی یا بەرز)',
    coreAir: 'هەوا (بێ ناڤۆک)',
    coreSteel: 'پۆڵا',
    liftingForce: 'هێزا کێشکرنێ / بارستەیا بلندکری (m_lifted)',
    biotSavartLaw: 'یاسایا بیۆ-ساڤار و ئەمپێر: B = μ · n · I',
    testAttraction: 'کێشکرنا پارچان تاقی بکە 🧲',
    reset: 'ژ نوی رێکبێخە',
    varLiftingForce: 'هێزا کێشکرنا کارۆموگناتیسێ (F)',
    notesText: 'کارتێکرنا تەزوو و بادانان ل سەر هێزا موگناتیسی هاتە تۆمارکرن.',
    controlsTitle: 'رێکخستنێن تاقیکرنا کارۆموگناتیسێ'
  },
  electromagnetic_induction: {
    title: 'کاریگەریا کارۆموگناتیسی و یاسایا فارادای',
    shortDesc: 'ڤەکۆلینا دروستبوونا تەزوویا هاندەر د کۆیلەکێدا ب رێکا لڤاندنا موگناتیسێ، یاسایا فارادای و یاسایا لێنز بۆ دیارکرنا ئاراستەیا تەزوویێ.',
    magnetSpeed: 'لەزاتیا لڤینا موگناتیسێ (v)',
    magnetStrength: 'هێزا موگناتیسێ (B)',
    coilTurns: 'ژمارەیا بادانێن کۆیلێ (N)',
    coilArea: 'رووبەرێ کۆیلێ (A)',
    inducedEMF: 'هێزا دەفعدەرا کارەبایی یا هاندەر (ε = -N · ΔΦ/Δt)',
    inducedCurrent: 'تەزوویا هاندەر (I_ind)',
    magneticFlux: 'تەوژما موگناتیسی (Φ = B · A · cos θ)',
    lenzLawNote: 'یاسایا لێنز: تەزوویا هاندەر بیاڤەکێ موگناتیسی دروست دکەت کو دژی گوهۆڕینا تەوژمێیە.',
    galvanometerDeflection: 'لادانا دەرزییا گالڤانۆمەتەرێ',
    moveMagnetIn: 'موگناتیسێ ببە ناڤ کۆیلێ ➡️',
    moveMagnetOut: 'موگناتیسێ ژ کۆیلێ دەربینە ⬅️',
    bulbGlow: 'درەوشانەوەیا گلۆپی ب هاندانا کارەبایی 💡',
    reset: 'ژ نوی رێکبێخە',
    varInducedEMF: 'هێزا دەفعدەرا کارەبایی یا هاندەر (ε)',
    notesText: 'دروستبوونا هێزا دەفعدەرا هاندەر و یاسایا فارادای ب دروستی هاتە سەلماندن.',
    controlsTitle: 'رێکخستنێن هاندانا کارۆموگناتیسی'
  },
  energy_skate_park: {
    title: 'پارکا سکتینگی و پاراستنا وزەیێ',
    shortDesc: 'ڤەکۆلینا گوهۆڕینا وزەیا لڤینێ، وزەیا پۆتەنسیال و وزەیا گەرمیێ (لێکخشین) بۆ سکتەربازی ل سەر رێڕەوێن جودا (U-شێوە، لووپ، رێکا لێژ).',
    skaterMass: 'بارستەیا سکتەربازی (m)',
    trackFriction: 'لێکخشینا رێڕەوی (Friction μ)',
    gravity: 'کێشکرن (g)',
    trackShape: 'شێوەیێ رێڕەوی',
    trackU: 'شێوەیێ پیتی U (ڕێڕەوێ کاسەیی)',
    trackLoop: 'لووپا بازنەیی (Loop-the-Loop)',
    trackRamp: 'ڕوویێ لێژ و بازدان (Jump Ramp)',
    trackWave: 'رێڕەوێ پێلدار (Double Valley)',
    kineticEnergy: 'وزەیا لڤینێ (KE = ½mv²)',
    potentialEnergy: 'وزەیا پۆتەنسیال (PE = mgh)',
    thermalEnergy: 'وزەیا گەرماتیێ ژ لێکخشینێ (E_th)',
    totalEnergy: 'کۆما وزەیێ (E_total)',
    skaterSpeed: 'لەزاتیا سکتەربازی (v)',
    skaterHeight: 'بلنداهیا سکتەربازی (h)',
    pieChart: 'دیاگراما بازنەیی یا وزەیێ',
    barChart: 'هێلکاریا ستوونی یا وزەیێ',
    showSpeedometer: 'پێوەری لەزاتیێ نیشان بدە',
    dropSkater: 'سکتەربازی دانە سەر رێڕەوی 🛹',
    reset: 'ژ نوی رێکبێخە',
    varTotalEnergy: 'کۆما وزەیا سیستەمی (E)',
    notesText: 'پاراستنا وزەیا میکانیکی و کاریگەریا لێکخشینێ ب سەرکەفتیانە هاتە تۆمارکرن.',
    controlsTitle: 'رێکخستنێن پارکا سکتینگی'
  },
  forces_motion: {
    title: 'یاسایێن نیوتنی یێن لڤینێ و هێز',
    shortDesc: 'ڤەکۆلینا یاسایا ئێکێ و دوویێ یا نیوتنی، پەیوەندیا د ناڤبەرا کۆما هێزان (ΣF)، بارستە (m) و لەزدانێ (a) دا، دگەل لێکخشینا تەختەیی.',
    appliedForce: 'هێزا سەپاندی (F_applied)',
    frictionForce: 'هێزا لێکخشینێ (F_friction = μ · N)',
    objectMass: 'بارستەیا قوتیێ (m)',
    netForce: 'کۆما هێزێن کارپێکەر (ΣF = F_app - f)',
    acceleration: 'لەزدان (a = ΣF / m)',
    velocity: 'لەزاتی (v)',
    surfaceType: 'جورێ رویێ ئەردی',
    surfaceIce: 'بەفر (بێ لێکخشین μ = 0)',
    surfaceWood: 'تەختە (لێکخشینا ناڤین μ = 0.3)',
    surfaceRough: 'کۆنکرێت (لێکخشینا زۆر μ = 0.6)',
    newtonSecondLaw: 'یاسایا دوویێ یا نیوتنی: ΣF = m · a',
    reset: 'ژ نوی رێکبێخە',
    varAcceleration: 'لەزدانا تەنێ (a)',
    notesText: 'یاسایێن نیوتنی و پەیوەندیا هێز و لەزدانێ ب سەرکەفتیانە هاتنە سەلماندن.',
    controlsTitle: 'رێکخستنێن هێز و لڤینێ'
  },
  fourier_making_waves: {
    title: 'شیکاریا فۆریێ و لێکدانا پێلان',
    shortDesc: 'ڤەکۆلینا پێکهاتەیێن شەپۆلێن ئاڵۆز ژ کۆما شەپۆلێن ساین و کۆساین (هارمۆنیکان)، شیکاریا فۆریێ و چێکرنا شەپۆلێن چوارگۆشە و ددانە-مشار.',
    fundamentalFreq: 'فریکوێنسیا بنەڕەتی (f₁)',
    harmonicsCount: 'ژمارەیا هارمۆنیکان (n)',
    waveformType: 'جورێ شەپۆلا ئارمانج',
    waveSquare: 'شەپۆلا چوارگۆشە (Square Wave)',
    waveSawtooth: 'شەپۆلا ددانە-مشار (Sawtooth Wave)',
    waveTriangle: 'شەپۆلا سێگۆشەیی (Triangle Wave)',
    amplitudeH1: 'فراوانیا هارمۆنیکا 1 (A₁)',
    amplitudeH2: 'فراوانیا هارمۆنیکا 2 (A₂)',
    amplitudeH3: 'فراوانیا هارمۆنیکا 3 (A₃)',
    fourierFormula: 'زنجیرەیا فۆریێ: f(t) = Σ A_n · sin(2π n f₁ t)',
    superpositionWave: 'شەپۆلا لێکدراو (Superposed Wave)',
    playAudioWave: 'دەنگێ شەپۆلێ ببیهیزە 🎵',
    reset: 'ژ نوی رێکبێخە',
    varHarmonicsCount: 'ژمارەیا هارمۆنیکێن بەشدار (n)',
    notesText: 'شیکاریا فۆریێ و لێکدانا شەپۆلان ب سەرکەفتیانە هاتە ئەنجامدان.',
    controlsTitle: 'رێکخستنێن شیکاریا فۆریێ'
  },
  gravity_force_lab: {
    title: 'تاقیگەها هێزا کێشکرنێ یا گەردوونی',
    shortDesc: 'ڤەکۆلینا یاسایا کێشکرنا گشتی یا نیوتنی د ناڤبەرا دوو تەناندا (F = G · m₁m₂ / r²)، کارتێکرنا بارستەی و دووراتیێ.',
    mass1: 'بارستەیا تەنێ ئێکێ (m₁)',
    mass2: 'بارستەیا تەنێ دوویێ (m₂)',
    distance: 'دووراتیا ناڤبەرا سەنتەران (r)',
    gravitationalForce: 'هێزا کێشکرنێ (F = G · m₁ · m₂ / r²)',
    newtonGravityLaw: 'یاسایا نیوتنی یا کێشکرنا گەردوونی',
    gravitationalConstant: 'نەگۆڕێ کێشکرنێ: G = 6.674 × 10⁻¹¹ N·m²/kg²',
    showForceVectors: 'ڤێکتەرێن هێزا کێشکرنێ نیشان بدە',
    reset: 'ژ نوی رێکبێخە',
    varGravitationalForce: 'هێزا کێشکرنێ د ناڤبەرا دوو بارستەیاندا (F)',
    notesText: 'هێزا کێشکرنێ و یاسایا چوارگۆشەیا پێچەوانە ب دروستی هاتنە سەلماندن.',
    controlsTitle: 'رێکخستنێن تاقیگەها هێزا کێشکرنێ'
  }
};
