export const batch2: Record<string, any> = {
  pendulum_energy: {
    title: 'پاراستنا وزەیێ د پاندۆلێدا',
    shortDesc: 'ڤەکۆلینا گوهۆڕینا بەردەوام د ناڤبەرا وزەیا لڤینێ (KE) و وزەیا پۆتەنسیال (PE) دا و سەلماندنا نەگۆڕیا وزەیا میکانیکی یا گشتی.',
    initialAngle: 'گۆشەیا دەستپێکێ (θ₀)',
    pendulumLength: 'درێژیا دەزووی (L)',
    bobMass: 'بارستەیا پاندۆلێ (m)',
    kineticEnergy: 'وزەیا لڤینێ (KE = ½mv²)',
    potentialEnergy: 'وزەیا پۆتەنسیال (PE = mgh)',
    totalEnergy: 'کۆما وزەیێ (E = KE + PE)',
    velocity: 'لەزاتیا گافی (v)',
    height: 'بلنداهیا ژ خالا بنەڕەت (h)',
    energyConservation: 'پاراستنا وزەیێ: E = const',
    energyChart: 'هێلکاریا ستوونی یا وزەیێ',
    speedVsAngle: 'لەزاتی بەرامبەر گۆشەیێ',
    frictionAir: 'لێکخشینا هەوای (Damping)',
    noFriction: 'بێ لێکخشین (پاراستنا تەواو)',
    resetPendulum: 'پاندۆلێ ژ نوی رێکبێخە',
    varTotalEnergy: 'کۆما وزەیا میکانیکی (E)',
    notesText: 'وزەیا میکانیکی یا پاندۆلێ ب دروستی هاتە حسابکرن و سەلماندن.',
    equilibriumSpeed: 'لەزاتی د خالا هەڤسەنگیێدا',
    maxPotentialHeight: 'بلنداهیا هەرە زێدە',
    controlsTitle: 'رێکخستنێن تاقیکرنا وزەیا پاندۆلێ',
    reset: 'ژ نوی رێکبێخە'
  },
  photoelectric_effect: {
    title: 'دیاردەیا کارۆرووناهی و تیۆرا فۆتۆنان',
    shortDesc: 'ڤەکۆلینا دەرپەڕینا ئەلیکترۆنان ب هۆی رووناهیێ، وزەیا فۆتۆنان، نەخشی ئیش (داللا کارێ)، پۆتەنسیالا راوەستاندنێ و لەزاتیا زێدە.',
    lightFrequency: 'فریکوێنسیا رووناهیێ (f)',
    lightIntensity: 'چڕیا رووناهیێ (Intensity)',
    targetMetal: 'ماددەیێ کانزای (Target Metal)',
    workFunction: 'نەخشی ئیش / داللا کارێ (Φ)',
    stoppingVoltage: 'جوداهیا پۆتەنسیالا راوەستاندنێ (V_stop)',
    photocurrent: 'تەزوویا کارۆرووناهیێ (I_photo)',
    maxKineticEnergy: 'وزەیا لڤینێ یا هەرە مەزن (KE_max)',
    electronEjection: 'ئەلیکترۆنێن دەرپەڕیو',
    thresholdFrequency: 'فریکوێنسیا دەستپێکێ (f₀)',
    cutoffWavelength: 'درێژیا پێلێ یا دەستپێکێ (λ₀)',
    einsteinEquation: 'هاوکێشەیا ئاینشتاین: KE_max = hf - Φ',
    logged: 'هاتە تۆمارکرن ✓',
    metals: 'کانزایێن ستاندارد (سۆدیۆم، زینک، مس، پلاتین، سێزیۆم)',
    varKEmax: 'وزەیا لڤینێ یا هەرە مەزن (KE_max)',
    notesText: 'پێڤانا وزەیا لڤینێ یا ئەلیکترۆنێن دەرپەڕیو ب سەرکەفتیانە هاتە تۆمارکرن.',
    controlsTitle: 'رێکخستنێن دیاردەیا کارۆرووناهیێ',
    wavelengthSlider: 'درێژیا پێلا رووناهیێ (λ)',
    voltageBias: 'ڤۆڵتیەیا دژی (Retarding Voltage)',
    reset: 'ژ نوی رێکبێخە',
    stoppingPotential: 'پۆتەنسیالا راوەستاندنێ',
    pause: 'راوەستاندن'
  },
  radioactive_decay: {
    title: 'شیبوونەڤەیا تیشکدەر و نیڤا ژیانێ',
    shortDesc: 'ڤەکۆلینا شیبوونەڤەیا ئەتۆمێن تیشکدەر، یاسایا نیڤا ژیانێ (t½)، نەگۆڕێ شیبوونەڤەیێ و کێمبوونا ژمارەیا ناڤۆکان ب رێکا ئەزموونا هەڕەمەکی.',
    isotope: 'ئایزۆتۆپێ تیشکدەر',
    halfLife: 'نیڤا ژیانێ (t½)',
    initialNuclei: 'ژمارەیا ناڤۆکێن دەستپێکێ (N₀)',
    decayConstant: 'نەگۆڕێ شیبوونەڤەیێ (λ)',
    elapsedTime: 'دەمێ دەربازبووی (t)',
    remainingNuclei: 'ناڤۆکێن ماین (N)',
    decayedNuclei: 'ناڤۆکێن شیبووین (N_decayed)',
    activity: 'چالاکیا تیشکدەری (Activity A)',
    decayFormula: 'هاوکێشە: N(t) = N₀ · e^(-λt) = N₀ · (½)^(t/t½)',
    startDecay: 'دەست ب شیبوونەڤەیێ بکە',
    pauseDecay: 'شیبوونەڤەیێ براوەستینە',
    reset: 'ژ نوی رێکبێخە',
    stepDecay: 'ئێک نیڤا ژیانێ دەرباز بکە',
    decayChart: 'هێلکاریا شیبوونەڤەیا تیشکدەر',
    logged: 'هاتە تۆمارکرن ✓',
    varRemaining: 'ژمارەیا ناڤۆکێن ماین (N)',
    notesText: 'پێڤانا شیبوونەڤەیا تیشکدەر و نیڤا ژیانێ هاتە تۆمارکرن.',
    controlsTitle: 'رێکخستنێن شیبوونەڤەیا تیشکدەر',
    initialCountLabel: 'ژمارەیا دەستپێکێ یا ناڤۆکان',
    logMeasurement: 'تۆمارکرنا پێڤانێ'
  },
  rotational_dynamics: {
    title: 'داینامیکا زڤڕینێ و زەڤرێ سستیێ',
    shortDesc: 'ڤەکۆلینا زەڤرێ زڤڕینێ (Torque)، زەڤرێ سستیێ (Moment of Inertia)، لەزدانا گۆشەیی و یاسایا دوویێ یا نیوتنی بۆ لڤینا زڤڕینێ.',
    torque: 'زەڤرێ زڤڕینێ (τ = r · F · sin θ)',
    inertia: 'زەڤرێ سستیێ (I)',
    angularAcceleration: 'لەزدانا گۆشەیی (α = τ / I)',
    angularVelocity: 'لەزاتیا گۆشەیی (ω)',
    radius: 'نیڤتیرە (r)',
    appliedForce: 'هێزا سەپاندی (F)',
    geometryShape: 'شێوەیێ ئەندازەیی یێ تەنێ',
    geoDisk: 'دیسکا تژی (I = ½mr²)',
    geoRing: 'حەلەقە (I = mr²)',
    geoSphere: 'تۆپکا تژی (I = ⅖mr²)',
    geoRodCenter: 'داریلکا درێژ ژ ناڤەندی (I = 1/12 ml²)',
    geoRodEnd: 'داریلکا درێژ ژ دووماهیێ (I = ⅓ ml²)',
    mass: 'بارستەیا تەنێ (m)',
    rotationalKE: 'وزەیا لڤینا زڤڕینێ (KE_rot = ½Iω²)',
    secondLawRot: 'یاسایا نیوتنی یا زڤڕینێ: Στ = Iα',
    startRotation: 'دەست ب زڤڕینێ بکە',
    brakeRotation: 'فرێنا زڤڕینێ',
    reset: 'ژ نوی رێکبێخە',
    varAngularAcc: 'لەزدانا گۆشەیی (α)',
    notesText: 'زەڤرێ سستیێ و لەزدانا گۆشەیی ب دروستی هاتنە حسابکرن.',
    controlsTitle: 'رێکخستنێن داینامیکا زڤڕینێ'
  },
  viscosity_stokes: {
    title: 'یاسایا ستۆکس و خەستییا شلەمەنیان',
    shortDesc: 'ڤەکۆلینا کەفتنا تۆپکەکا کانزایی د ناڤ شلەمەنیەکا خەستدا، هێزا لێکخشینا ناڤەکی و لەزاتیا دووماهیکێ (Terminal Velocity).',
    fluidViscosity: 'کۆلکێ خەستیێ (Viscosity η)',
    sphereRadius: 'نیڤتیرەیا تۆپکێ (r)',
    sphereDensity: 'چڕیا تۆپکێ (ρ_s)',
    fluidDensity: 'چڕیا شلەمەنیێ (ρ_f)',
    terminalVelocity: 'لەزاتیا دووماهیکێ (v_t)',
    dragForce: 'هێزا بەرگریێ یا ستۆکس (F_d = 6πηrv)',
    stokesLaw: 'یاسایا ستۆکس: F_d = 6πηrv',
    dropBall: 'تۆپکێ بەردە ناڤ شلەمەنیێ 💧',
    reset: 'ژ نوی رێکبێخە',
    varTerminalVel: 'لەزاتیا دووماهیکێ یا تۆپکێ (v_t)',
    notesText: 'لەزاتیا دووماهیکێ د ناڤ شلەمەنیێدا ب سەرکەفتیانە هاتە پێڤان.',
    controlsTitle: 'رێکخستنێن خەستیا شلەمەنیان',
    fluidSelect: 'هەلبژارتنا شلەمەنیێ (گلیسیرین، رۆن، ئاڤ)',
    logged: 'هاتە تۆمارکرن ✓'
  },
  acoustic_resonance: {
    title: 'دەنگڤەدانا دەنگی د بۆڕیێن هەوایدا',
    shortDesc: 'ڤەکۆلینا دەنگڤەدانێ د بۆڕیێن سەرڤەکری و سەردائێخستیدا، لەرینێن ل دویف ئێک، فریکوێنسیا بنەڕەتی و لەزاتیا دەنگی د هەوایدا.',
    tubeType: 'جورێ بۆڕیێ',
    tubeOpen: 'بۆڕیا ژ هەردوو سەران ڤەکری',
    tubeClosed: 'بۆڕیا ژ ئێک سەری دائێخستی',
    tubeLength: 'درێژیا بۆڕیێ (L)',
    soundSpeed: 'لەزاتیا دەنگی د هەوایدا (v)',
    fundamentalFreq: 'فریکوێنسیا بنەڕەتی (f₁)',
    harmonicOrder: 'پلەیا لەرینێ (Harmonic n)',
    currentHarmonic: 'فریکوێنسیا دەنگڤەدانێ (f_n)',
    antinodesNodes: 'گرێ و دژەگرێیێن پەستانێ',
    resonanceCondition: 'مەرجێ دەنگڤەدانێ هاتە دیارکرن 🔊',
    playResonanceTone: 'دەنگێ دەنگڤەدانێ لێدە',
    stopTone: 'دەنگی براوەستینە',
    reset: 'ژ نوی رێکبێخە',
    varFundamentalFreq: 'فریکوێنسیا دەنگڤەدانێ (f)',
    notesText: 'دەنگڤەدانا بۆڕیا دەنگی و فریکوێنسیا لەرینێ ب دروستی هاتە پێڤان.',
    controlsTitle: 'رێکخستنێن دەنگڤەدانا دەنگی',
    frequencySlider: 'فریکوێنسیا لەرینەرا دەنگی'
  },
  angled_mirrors: {
    title: 'ئاڤینکێن گۆشەدار و وێنەیێن گەلەک',
    shortDesc: 'ڤەکۆلینا ژمارەیا وێنەیێن دروستبووی د ناڤبەرا دوو ئاڤینکێن تەختدا دەمێ گۆشەیا ناڤبەرا وان دهێتە گوهۆڕین.',
    mirrorAngle: 'گۆشەیا ناڤبەرا دوو ئاڤینکان (θ)',
    imageCount: 'ژمارەیا وێنەیان (N = 360°/θ - 1)',
    formulaAngle: 'هاوکێشە: N = (360° / θ) - 1',
    symmetricObject: 'تەن ل سەر هێلا نیڤکەرێ گۆشەیێیە',
    asymmetricObject: 'تەن د جهەکێ نەهەڤسەنگدایە',
    presets: 'گۆشەیێن ستاندارد (120°, 90°, 72°, 60°, 45°, 30°)',
    parallelMirrors: 'ئاڤینکێن تەریب (θ = 0° -> بی دووماهی وێنە)',
    reset: 'ژ نوی رێکبێخە',
    varImageCount: 'ژمارەیا وێنەیێن دروستبووی (N)',
    notesText: 'ژمارەیا وێنەیان د ناڤبەرا دوو ئاڤینکاندا ب سەرکەفتیانە هاتە پێڤان.',
    controlsTitle: 'رێکخستنێن ئاڤینکێن گۆشەدار',
    rayTrace: 'نیشاندانا تیشکێن ڕەنگڤەداوی'
  },
  arc_length: {
    title: 'درێژیا کەڤانی، رادیەن و لڤینا بازنەیی',
    shortDesc: 'ڤەکۆلینا پەیوەندیا ناڤبەرا گۆشەیا رادیەن، نیڤتیرەیا بازنەیی و درێژیا کەڤانێ بڕی (s = r · θ).',
    radius: 'نیڤتیرەیا بازنەیی (r)',
    angleDegree: 'گۆشە ب پلە (θ_deg)',
    angleRadian: 'گۆشە ب رادیەن (θ_rad = θ · π/180)',
    arcLength: 'درێژیا کەڤانی (s = r · θ)',
    sectorArea: 'رووبەرێ کەرتێ بازنەیی (A = ½r²θ)',
    fullCircle: 'سووڕا تەواو (360° = 2π rad)',
    semiCircle: 'نیڤا بازنەیی (180° = π rad)',
    quarterCircle: 'چوارێکا بازنەیی (90° = π/2 rad)',
    radianDefinition: 'پێناسەیا رادیەنێ: دەمێ s = r ببیتی گۆشە دبیتە 1 rad (~57.3°)',
    reset: 'ژ نوی رێکبێخە',
    varArcLength: 'درێژیا کەڤانی (s)',
    notesText: 'پەیوەندیا ناڤبەرا رادیەن و کەڤانی ب دروستی هاتە دیارکرن.',
    controlsTitle: 'رێکخستنێن کەڤانێ بازنەیی'
  },
  atomic_spectra: {
    title: 'سپێکتڕۆما گەردیلەی و گواستنەوەیا بۆهر',
    shortDesc: 'ڤەکۆلینا سپێکتڕۆما دەرپەڕین و مژینێ یا گەردیلەیا هایدرۆجینێ، بازدانا ئەلیکترۆنان د ناڤبەرا ئاستێن وزەیێدا و زنجیرەیێن بۆهر، لایمان، باڵمەر و پاشن.',
    initialLevel: 'ئاستێ وزەیێ یێ دەستپێکێ (n_i)',
    finalLevel: 'ئاستێ وزەیێ یێ دووماهیکێ (n_f)',
    photonEnergy: 'وزەیا فۆتۆنی (ΔE = E_f - E_i)',
    photonWavelength: 'درێژیا پێلا فۆتۆنی (λ = hc/ΔE)',
    emissionMode: 'دەرپەڕینا تیشکێ (Emission)',
    absorptionMode: 'مژینا تیشکێ (Absorption)',
    seriesLyman: 'زنجیرەیا لایمان (UV, n_f = 1)',
    seriesBalmer: 'زنجیرەیا باڵمەر (Visible, n_f = 2)',
    seriesPaschen: 'زنجیرەیا پاشن (Infrared, n_f = 3)',
    seriesBrackett: 'زنجیرەیا براکێت (Infrared, n_f = 4)',
    rydbergFormula: 'هاوکێشەیا ریدبێرگ: 1/λ = R_H (1/n₁² - 1/n₂²)',
    spectralLineColor: 'رەنگێ هێلا سپێکتڕۆمی',
    showBohrOrbit: 'نیشاندانا خولگەیێن بۆهری',
    triggerTransition: 'ئەلیکترۆنێ ڤەگوهێزە ⚛️',
    reset: 'ژ نوی رێکبێخە',
    varWavelength: 'درێژیا پێلا سپێکتڕۆمی (λ)',
    notesText: 'بازدانا ئەلیکترۆنی و درێژیا پێلا سپێکتڕۆمی ب سەرکەفتیانە هاتە پێڤان.',
    controlsTitle: 'رێکخستنێن سپێکتڕۆما گەردیلەی'
  },
  bernoulli: {
    title: 'بنەمایێ بێرنۆلی و بۆڕیا ڤێنتۆری',
    shortDesc: 'ڤەکۆلینا لڤینا شلەمەنیان، پەیوەندیا د ناڤبەرا لەزاتی و پەستانێ د بۆڕیەکێدا ب رووبەرێن جودا و یاسایا بەردەوامیا شلەمەنیان.',
    flowRate: 'تێکڕایا رژانێ (Flow Rate Q = A · v)',
    area1: 'رووبەرێ پشکا بەرین (A₁)',
    area2: 'رووبەرێ پشکا تەنگ (A₂)',
    speed1: 'لەزاتی د پشکا بەریندا (v₁)',
    speed2: 'لەزاتی د پشکا تەنگدا (v₂)',
    pressure1: 'پەستان د پشکا بەریندا (P₁)',
    pressure2: 'پەستان د پشکا تەنگدا (P₂)',
    pressureDiff: 'جوداهیا پەستانێ (ΔP = P₁ - P₂)',
    continuityEquation: 'یاسایا بەردەوامیێ: A₁v₁ = A₂v₂',
    bernoulliEquation: 'بنەمایێ بێرنۆلی: P + ½ρv² + ρgh = const',
    reset: 'ژ نوی رێکبێخە',
    varPressureDiff: 'جوداهیا پەستانێ د بۆڕیا ڤێنتۆریدا (ΔP)',
    notesText: 'پەیوەندیا پەستان و لەزاتیا شلەمەنیێ ب دروستی هاتە سەلماندن.',
    controlsTitle: 'رێکخستنێن بنەمایێ بێرنۆلی'
  }
};
