export const batch1: Record<string, any> = {
  pendulum: {
    title: 'پاندۆلا سادە و لەرزین',
    shortDesc: 'ڤەکۆلینا دەمێ لەرینێ (T)، کارتێکرنا درێژیا دەزووی، بارستە و گۆشەیا دەستپێکێ ل سەر پاندۆلا سادە.',
    length: 'درێژیا بەندکی (L)',
    mass: 'بارستەیا پاندۆلێ (m)',
    gravity: 'کێشکرن (g)',
    initialAngle: 'گۆشەیا دەستپێکێ (θ₀)',
    damping: 'کێمبوونا لەرینێ (لێکخشینا هەوای)',
    theoreticalPeriod: 'دەمێ تیۆری یێ لەرینێ (T)',
    currentAngle: 'گۆشەیا نوکە (θ)',
    periodT: 'دەمێ لەرینێ T',
    realTime: 'دەمێ نوکە',
    angularVelocity: 'لەزاتیا گۆشەیی ω',
    kineticEnergy: 'وزەیا لڤینێ',
    potentialEnergy: 'وزەیا پۆتەنسیال',
    totalEnergy: 'کۆما وزەیێ',
    chartTitle: 'هێلکاریا پێلێ (گۆشە - دەم)',
    smallAngleWarning: '⚠️ گۆشە ژ 15° مەزنترە: هاوکێشەیا تەنها ب نزیکی یا دروستە (سیمولەیشن هاوکێشەیا دروست یا ناهێلی بکاردئینیت).',
    varPeriod: 'دەمێ لەرینا پاندۆلا سادە (T)',
    notesText: 'پێڤانا دەمێ لەرینێ دبن گۆشە و مەرجێن جودادا ب دروستی هاتە ئەنجامدان.',
    dragHint: 'ب ماوسی بارستەیێ پاندۆلێ رابکێشە دا کو دەست ب لەرینێ بکەت.',
    resetParams: 'رێکخستنێن بنەڕەتی'
  },
  spring: {
    title: 'یاسایا هووک و لەرینەرا سپرینگێ',
    subTitle: 'یاسایا هووک و لەرینا سپرینگێ',
    shortDesc: 'ڤەکۆلینا درێژبوون و گوشارانا سپرینگێ، نەگۆڕێ سپرینگێ k، دەمێ لەرینێ و وزەیا پۆتەنسیالا تەشیاری.',
    springConstant: 'نەگۆڕێ سپرینگێ (k)',
    mass: 'بارستەیا هەلاویستی (m)',
    displacement: 'لادانا دەستپێکێ (x₀)',
    damping: 'کێمبوونا لەرینێ (بەرگریا هەوای)',
    orientation: 'ئاراستەیا سپرینگێ',
    vertical: 'ستوونی',
    horizontal: 'ئاسۆیی',
    theoreticalPeriod: 'دەمێ تیۆری یێ لەرینێ (T)',
    pullMass: 'بارستەی ب ماوسی رابکێشە یان رێکخستنێ بگوهۆڕە',
    totalEnergy: 'کۆما وزەیا میکانیکی (E_total)',
    eqPos: 'جهێ هەڤسەنگیێ x = 0',
    eqPosShort: 'هەڤسەنگی x = 0',
    dispX: 'لادان x',
    velV: 'لەزاتی v',
    restoringF: 'هێزا ڤەگێڕ F',
    kineticEnergy: 'وزەیا لڤینێ',
    elasticPotential: 'وزەیا پۆتەنسیالا تەشیاری',
    showVectors: 'ڤێکتەران نیشان بدە',
    energyChart: 'هێلکاریا وزەیێ',
    oscillatorParams: 'پێوەرێن سپرینگ و بارستەیێ',
    theoreticalAnalysis: 'ئەنجام و شڕۆڤەیا تیۆری',
    naturalFreq: 'فریکوێنسیا سروشتی f₀',
    angularFreq: 'لەزاتیا گۆشەیی ω',
    loggedSuccess: 'هاتە تۆمارکرن ✓',
    logData: 'پێڤانێ تۆمار بکە',
    play: 'دەستپێکرن',
    pause: 'راوەستاندن',
    reset: 'ژ نوی رێکبێخە',
    variableName: 'دەمێ لەرینا لەرینەرێ (T)',
    notes: 'تاقیکرنا لەرینەرا سادە یا بارستەیا m ل سەر سپرینگێ.'
  },
  buoyancy: {
    title: 'بنەمایێ ئەرشەمیدس و هێزا بلندکرنا شلەمەنیان',
    shortDesc: 'ڤەکۆلینا سەرئاڤکەفتن و نوقمبوونا تەنان، قەبارێ د بن ئاڤێدا، کێشێ دیار و چڕیا شلەمەنیان.',
    fluidType: 'جورێ شلەمەنیێ',
    fluidDensity: 'چڕیا شلەمەنیێ (ρ_fluid)',
    objectMaterial: 'ماددەیێ تەنێ',
    objectDensity: 'چڕیا تەنێ (ρ_obj)',
    objectVolume: 'قەبارێ تەنێ (V)',
    objectMass: 'بارستەیا تەنێ (m)',
    actualWeight: 'کێشێ دروست د هەوایدا (W = mg)',
    buoyantForce: 'هێزا بلندکرنێ بەرەڤ ژۆر (F_b = ρ_f·V_sub·g)',
    apparentWeight: 'کێشێ دیار د شلەمەنیێدا (W_app)',
    submergedVolume: 'قەبارێ نوقمبووی (V_sub)',
    submergedPercent: 'ڕێژەیا نوقمبوونێ (%)',
    statusFloating: '🟢 تەن ل سەر ئاڤێ دمینیت (ρ_obj < ρ_fluid)',
    statusNeutral: '🟡 د ناڤ شلەمەنیێدا یا هەلاویستییە (ρ_obj = ρ_fluid)',
    statusSinking: '🔴 تەن بەرەڤ بنێ نوقم دبیت (ρ_obj > ρ_fluid)',
    waterDisplaced: 'شلەمەنیا دەرچووی د قاپکێدا',
    overflowBeaker: 'قاپکێ دەرچوونێ',
    scaleLabel: 'تەرازوو',
    materialFluidConfig: 'تایبەتمەندیێن تەن و شلەیێ',
    naturalEquilibrium: 'هاوسەنگیا سروشتی یا فیزیایێ',
    manualImmersion: 'نوقمکرنا ب دەستی',
    archimedesLaw: 'یاسایا ئەرشەمیدسی',
    buoyantForceVar: 'هێزا بلندکرنا بەرەڤ ژۆر (F_b)'
  },
  collision: {
    title: 'پێکدادان د ئێک رەهەنددا و پاراستنا تەوژمێ',
    shortDesc: 'ڤەکۆلینا لێککەفتنا نەرم و رەق د ناڤبەرا دوو تەناندا، پاراستنا تەوژمێ (تەخما)، وزەیا لڤینێ و کۆلکێ ڤەگەڕیانێ.',
    cart1: 'عەرەبانکا ئێکێ (m₁)',
    cart2: 'عەرەبانکا دوویێ (m₂)',
    elasticity: 'کۆلکێ ڤەگەڕیانێ (e)',
    elastic: 'پێکدادانا رەق (e = 1)',
    inelastic: 'پێکدادانا نەرم (e = 0)',
    partiallyElastic: 'پێکدادانا نیڤ-رەق (0 < e < 1)',
    totalMomentum: 'کۆما تەوژمێ پێش / پاش (P_total)',
    totalKineticEnergy: 'کۆما وزەیا لڤینێ (KE_total)',
    velocity1: 'لەزاتیا عەرەبانکا ئێکێ (v₁)',
    velocity2: 'لەزاتیا عەرەبانکا دوویێ (v₂)',
    momentumConserved: 'یاسایا پاراستنا تەوژمێ: P₁ + P₂ = P₁’ + P₂’',
    keConserved: 'وزەیا لڤینێ هاتیە پاراستن (پێکدادانا رەق)',
    keLost: 'وزەیا لڤینێ یا بەرزەبووی (بۆ گەرماتی یان شێوەگوهۆڕینێ چوو)',
    stepAction: 'پێنگاڤەک',
    energyLoss: 'رێژەیا بەرزەبوونا وزەیێ (%)',
    collisionComplete: 'پێکدادان ب سەرکەفتیانە ب دووماهیک هات',
    resetPositions: 'زڤڕاندنا جهێن عەرەبانکان',
    varMomentum: 'کۆما تەوژما لێککەفتنێ (P)'
  },
  thermodynamics: {
    title: 'یاسایا ئێکێ یا داینامیکا گەرمیێ و گازا نموونەیی',
    shortDesc: 'ڤەکۆلینا کار، گەرماتی، وزەیا ناڤەکی و پرۆسەیێن ترۆمپەیێ: قەبارە نەگۆڕ، پەستان نەگۆڕ، پلەیا گەرماتیێ نەگۆڕ و ئەدیاباتیک.',
    processType: 'جورێ پرۆسەیا داینامیکا گەرمیێ',
    isothermal: 'پلەیا گەرماتیێ نەگۆڕ (Isothermal, ΔT = 0)',
    isobaric: 'پەستان نەگۆڕ (Isobaric, P = const)',
    isochoric: 'قەبارە نەگۆڕ (Isochoric, V = const)',
    adiabatic: 'ئەدیاباتیک (Adiabatic, Q = 0)',
    pressure: 'پەستان (P)',
    volume: 'قەبارە (V)',
    temperature: 'پلەیا گەرماتیێ (T)',
    moles: 'ژمارەیا مۆلان (n)',
    workDone: 'ئیشێ ئەنجامدای (W)',
    heatAdded: 'گەرماتیا زێدەبووی (Q)',
    deltaU: 'گوهۆڕینا وزەیا ناڤەکی (ΔU)',
    firstLaw: 'یاسایا ئێکێ یا داینامیکا گەرمیێ: ΔU = Q - W',
    pvDiagram: 'دیاگراما پەستان-قەبارە (P-V Diagram)',
    heatPiston: 'گەرمکرنا ترۆمپەیێ (Q > 0)',
    coolPiston: 'سارکرنا ترۆمپەیێ (Q < 0)',
    compressPiston: 'گوشارانا ترۆمپەیێ (W < 0)',
    expandPiston: 'بەرفرەهبوونا ترۆمپەیێ (W > 0)',
    workEfficiency: 'شیانا گەرمیێ یا سووڕێ',
    varInternalEnergy: 'گوهۆڕینا وزەیا ناڤەکی (ΔU)'
  },
  projectile: {
    title: 'لڤینا هاوێژراوان د دوو رەهەنداندا',
    shortDesc: 'ڤەکۆلینا ئاراستەیا گوللێ، گۆشەیا دەستپێکێ، لەزاتیا دەستپێکێ، مەودایێ ئاسۆیی، بلنداهیا هەرە مەزن و بەرگریا هەوای.',
    velocity: 'لەزاتیا دەستپێکێ (v₀)',
    angle: 'گۆشەیا هاڤێتنێ (θ)',
    height: 'بلنداهیا دەستپێکێ (y₀)',
    airResistance: 'بەرگریا هەوای (Drag Coefficient)',
    launch: 'گوللەیێ باڤێژە 🚀',
    reset: 'ژ نوی رێکبێخە',
    maxHeight: 'بلنداهیا هەرە زێدە (H_max)',
    range: 'مەودایێ ئاسۆیی (R)',
    flightTime: 'دەمێ فڕینێ (t_flight)',
    vx: 'لەزاتیا ئاسۆیی (v_x)',
    vy: 'لەزاتیا ستوونی (v_y)',
    targetMode: 'رەوشا پێڕاگەهشتنا ئارمانجێ',
    targetDistance: 'دووراتیا ئارمانجێ (x_target)',
    hitTarget: 'ئارمانج هاتە پێکان! 🎯',
    missedTarget: 'بەر ئارمانجێ نەکەفت! ❌',
    varRange: 'مەودایێ ئاسۆیی یێ هاوێژراوی (R)',
    launchControlsTitle: 'رێکخستنێن هاڤێتنا گوللەیێ',
    notesText: 'تاقیکرنا هاڤێتنا گوللەیێ ب گۆشە و لەزاتیا جودا هاتە تۆمارکرن.'
  },
  circuits: {
    title: 'یاسایا ئۆم و بازنەیێن کارەبایی',
    shortDesc: 'سیمولەیشنا بازنەیا کارەبایی یا DC، پێڤانا ڤۆڵتیە، تەزوو، بەرگری و شیانا کارەبایی.',
    subtitle: 'ئاڤاکرنا بازنەیا DC، شیکاریا یاسایا ئۆمی، مولتیمەتەرا دیجیتالی، دیاگراما I-V و گەرماتیا جوول',
    voltage: 'ڤۆڵتیەیا سەرچاوەی (V)',
    resistance1: 'بەرگریا ئێکێ (R₁)',
    resistance2: 'بەرگریا دوویێ (R₂)',
    resistance3: 'بەرگریا سێیێ (R₃)',
    circuitType: 'جورێ گرێدانا بازنەیێ',
    series2: 'ل دویف ئێک (2 بەرگری)',
    series3: 'ل دویف ئێک (3 بەرگری)',
    parallel2: 'ب هەڤپشک (2 بەرگری)',
    parallel3: 'ب هەڤپشک (3 بەرگری)',
    mixed: 'تێکەل (R₁ + R₂||R₃)',
    lampCircuit: 'گلۆپ و بەرگریا گوهۆڕۆک',
    single: 'ئێک بەرگری (R₁)',
    series: 'ل دویف ئێک',
    parallel: 'ب هەڤپشک',
    switch: 'مفتاحا بازنەیێ',
    switchOn: 'بازنەیا گرتی (تەزوو یا هەی)',
    switchOff: 'بازنەیا ڤەکری (قوتکری)',
    toggleToOpen: 'کلیک بکە بۆ ڤەکرنا بازنەیێ (قوتکرنا تەزوویێ)',
    toggleToClose: 'کلیک بکە بۆ گرتنا بازنەیێ (گەیاندنا تەزوویێ)',
    canvasSwitchHint: 'کلیک ل سەر مفتاحی بکە بۆ گوهۆڕینێ',
    canvasOpenState: 'بازنەیا ڤەکری (تەزوو = 0)',
    canvasClosedState: 'بازنەیا گرتی (تەزوو یا هەی)',
    circuitOpenFormulaNote: 'بازنە یا ڤەکرییە: بەرگری بێدوماهییە (Req = ∞) و تەزوو سفرە (I = 0)',
    current: 'تەزوویا گشتی (I)',
    totalResistance: 'کۆما بەرگریێ (Req)',
    power: 'شیانا بکاربری (P)',
    bulbBrightness: 'رووناهی و گەرماتیا گلۆپی',
    multimeter: 'ئامیرێ مولتیمەتەر',
    probeAll: 'هەمی بازنە (گشتی)',
    probeR1: 'بەرگریا ئێکێ (R₁)',
    probeR2: 'بەرگریا دوویێ (R₂)',
    probeR3: 'بەرگریا سێیێ (R₃)',
    ammeter: 'ئەمپێرمەتەر (A)',
    voltmeter: 'ڤۆڵتمەتەر (V)',
    wattmeter: 'واتمەتەر (W)',
    ohmmeter: 'ئۆممەتەر (Ω)',
    flowType: 'نیشاندانا رەوتێ تەزوویێ',
    electronFlow: 'رەوتێ ئەلیکترۆنان (e⁻)',
    conventionalFlow: 'رەوتێ کلاسیک (+ بۆ -)',
    voltagePresets: 'ڤۆڵتیەیا ستاندارد',
    presetAA: '1.5V (پاتریا AA)',
    preset9V: '9.0V (پاتریا 9V)',
    preset12V: '12V (پاتریا ترۆمبێلێ)',
    preset24V: '24V (سەرچاوەیێ DC یێ تاقیگەهێ)',
    ivGraphTitle: 'دیاگراما یاسایا ئۆم (I-V Curve)',
    operatingPoint: 'خالا کارکرنێ یا نوکە',
    jouleHeat: 'رێژەیا گەرماتیا جوول',
    varTotalCurrent: 'تەزوویا گشتی یا بازنەیا کارەبایی (I)',
    notesText: 'یاسایا ئۆمی (V = I · R) و شیانا بەرزەبووی یا جوول (P = V · I = I² · R) هاتە سەلماندن.',
    componentSettingsTitle: 'رێکخستنێن پێکهاتێن بازنەیێ',
    liveCalculationsTitle: 'هژمارتنێن یاسایا ئۆمی پێنگاڤ ب پێنگاڤ:',
    tip: '💡 ڤۆڵتیێ یان بەرگریێ بگوهۆڕە دا کو بەلاڤبوونا تەزوویێ، هێزا گەرماتیێ و لڤینا خالا کارکرنێ ل سەر هێلا ئۆمی ببینی!'
  },
  optics: {
    title: 'یاسایا سنێل و شکەستنا رووناهیێ',
    shortDesc: 'ڤەکۆلینا شکەستنا تیشکا رووناهیێ، یاسایا سنێل، گۆشەیا رەخنەگر و ڕەنگڤەدانا تەماما ناڤەکی د ناڤبەرا دوو ناڤەنداندا.',
    medium1: 'ناڤەندێ ئێکێ (n₁)',
    medium2: 'ناڤەندێ دوویێ (n₂)',
    incidentAngle: 'گۆشەیا کەفتنێ (θ₁)',
    refractedAngle: 'گۆشەیا شکەستنێ (θ₂)',
    criticalAngle: 'گۆشەیا رەخنەگر (θ_c)',
    totalInternalReflection: '🔴 ڕەنگڤەدانا تەماما ناڤەکی روویدا (θ₁ > θ_c)',
    normalRefraction: '🟢 تیشک شکەست و دەرباز بوو',
    snellsLaw: 'یاسایا سنێل: n₁ · sin(θ₁) = n₂ · sin(θ₂)',
    lightSpeed1: 'لەزاتیا رووناهیێ د ناڤەندێ 1 دا (v₁)',
    lightSpeed2: 'لەزاتیا رووناهیێ د ناڤەندێ 2 دا (v₂)',
    showNormal: 'هێلا ستوون نیشان بدە (Normal Line)',
    showAngles: 'پلەیێن گۆشەیان نیشان بدە',
    refractionIndex: 'کۆلکێ شکەستنێ (Index of Refraction)',
    rayDiagram: 'دیاگراما تیشکێن رووناهیێ',
    presets: 'ناڤەندێن ستاندارد (هەوا، ئاڤ، زەیت، جام، ئەلماس)',
    varRefractedAngle: 'گۆشەیا شکەستنا رووناهیێ (θ₂)',
    notesText: 'پێڤانا گۆشەیا شکەستنێ و دیتنا گۆشەیا رەخنەگر ب دروستی هاتە ئەنجامدان.',
    laserControlsTitle: 'رێکخستنێن تیشکا لەیزەرێ',
    reflectionRay: 'تیشکا ڕەنگڤەداوی'
  },
  freefall: {
    title: 'کەفتنا سەرەبست و تاودانا کێشکرنێ',
    shortDesc: 'ڤەکۆلینا کەفتنا تەنان ژ بلنداهیێن جودا، کارتێکرنا بارستەی، لەزدانا کێشکرنێ ل سەر هەسارێن جودا و بەرگریا هەوای.',
    height: 'بلنداهیا کەفتنێ (h)',
    mass: 'بارستەیا تەنێ (m)',
    planetGravity: 'کێشکرنا هەسارێ (g)',
    airDrag: 'بەرگریا هەوای (Air Resistance)',
    dropObject: 'تەنێ بەردە 🍎',
    fallTime: 'دەمێ کەفتنێ (t)',
    impactVelocity: 'لەزاتیا گەهشتنێ ب ئەردی (v_final)',
    freefallFormula: 'هاوکێشە: h = ½gt² , v = gt',
    vacuumMode: 'ڤالاهی (بێ بەرگریا هەوای)',
    airMode: 'هەوایێ ئاسایی',
    featherVsHammer: 'پەڕ دژی چەکوجی (تاقیکرنا گالیلەی ل سەر هەیڤێ)',
    distanceTimeGraph: 'هێلکاریا بلنداهی - دەم',
    velocityTimeGraph: 'هێلکاریا لەزاتی - دەم',
    accelerationTimeGraph: 'هێلکاریا لەزدان - دەم',
    dropSuccess: 'تەن ب سەرکەفتیانە گەهشتە ئەردی!',
    varFallTime: 'دەمێ کەفتنا سەرەبست (t)',
    notesText: 'کەفتنا تەنێ ب کێشکرنا هەلبژارتی و حسابکرنا لەزاتیا دووماهیکێ هاتە تۆمارکرن.',
    dropControlsTitle: 'رێکخستنێن کەفتنا سەرەبست'
  },
  waves: {
    title: 'تایبەتمەندیێن پێلێن میکانیکی و درێژیا پێلێ',
    shortDesc: 'ڤەکۆلینا فریکوێنسی، درێژیا پێلێ، فراوانی و لەزاتیا بەلاڤبوونا پێلان د ناڤبەرەکا بەردەوامدا.',
    frequency: 'فریکوێنسی (f)',
    wavelength: 'درێژیا پێلێ (λ)',
    amplitude: 'فراوانیا پێلێ (A)',
    waveSpeed: 'لەزاتیا پێلێ (v = f · λ)',
    waveType: 'جورێ پێلێ (پێلا پان، پێلا درێژەکی)',
    transverse: 'پێلا پان (Transverse)',
    longitudinal: 'پێلا درێژەکی (Longitudinal)',
    waveEquation: 'هاوکێشەیا سەرەکی یا پێلان: v = f · λ',
    damping: 'کێمبوونا پێلێ',
    tension: 'گرژی د ناڤەندێدا',
    waveGraph: 'هێلکاریا پێلا نوکە',
    varWavelength: 'درێژیا پێلا پێڤای (λ)',
    notesText: 'پێوەندی د ناڤبەرا فریکوێنسی و درێژیا پێلێدا ب دروستی هاتە سەلماندن.'
  }
};
